### ISSUE TITLE
Archive Build Failure - Multiple commands produce GoogleToolboxForMac.framework

### ISSUE THREAD

**Issue by n3at18** [google/google-toolbox-for-mac#234] opened 2019-04-21 15:27 UTC
Hello!

I'm trying to "Archive" the project with new Xcode 10 build system and continuously getting the following error:

> Multiple commands produce '/Users/imac/Library/Developer/Xcode/DerivedData/LifeWheel-cdvlrefclgsttmagbvgjrlgavyih/Build/Intermediates.noindex/ArchiveIntermediates/LifeWheel/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleToolboxForMac.framework':
> 1) Target 'GoogleToolboxForMac-Defines-Logger-NSData+zlib' has create directory command with output '/Users/imac/Library/Developer/Xcode/DerivedData/LifeWheel-cdvlrefclgsttmagbvgjrlgavyih/Build/Intermediates.noindex/ArchiveIntermediates/LifeWheel/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleToolboxForMac.framework'
> 2) Target 'GoogleToolboxForMac-Defines-NSData+zlib' has create directory command with output '/Users/imac/Library/Developer/Xcode/DerivedData/LifeWheel-cdvlrefclgsttmagbvgjrlgavyih/Build/Intermediates.noindex/ArchiveIntermediates/LifeWheel/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleToolboxForMac.framework'

Is there any way to fix it / workaround?

Thank you!

**Comment by thomasvl** [comment] 2019-04-21 22:45
Why are you trying to archive GTM?  If you are trying to archive your product and using some of GTM, don't use the Xcode project as that will cause all of this code to be linked and odds are you only need a small subset of it.  Just add the sources you need to your project.

**Comment by n3at18** [comment] 2019-04-21 23:46
@thomasvl
Thanks for reply!
I’m archiving my project which has reference to Firebase pod which has reference to GTM. 
GTM references got added automatically.

**Comment by n3at18** [comment] 2019-04-23 03:04
> Why are you trying to archive GTM? If you are trying to archive your product and using some of GTM, don't use the Xcode project as that will cause all of this code to be linked and odds are you only need a small subset of it. Just add the sources you need to your project.

@thomasvl
Thanks for reply!
I’m archiving my project which has reference to Firebase pod which has reference to GTM.
GTM references got added automatically.

Is there any way to resolve the issue without adding sources to my project? Also I believe firebase still gonna install GTM even if I add it to my project.

**Comment by thomasvl** [comment] 2019-04-23 15:16
I'm not completely sure what the error is since what you are quoting looks more like a status line than an error.  It sounds like this could be an issue with CocoaPods then.  Maybe check if you have a current version installed, and/or see if they (or Firebase) have any docs/similar issues that might point to the cause/solution.

**Comment by n3at18** [comment] 2019-04-24 00:46
> I'm not completely sure what the error is since what you are quoting looks more like a status line than an error. It sounds like this could be an issue with CocoaPods then. Maybe check if you have a current version installed, and/or see if they (or Firebase) have any docs/similar issues that might point to the cause/solution.

Thank you so much for the response!
I've updated CocoaPods and issue go away.

**Comment by n3at18** [comment] 2019-04-24 02:29
Temporary switched to "Legacy Build System" and it has resolved the issue

**Comment by rafaelreis-hotmart** [comment] 2019-05-31 19:29
Same issue here!

**Comment by adamteale** [comment] 2019-06-04 16:47
same here!

**Comment by ugiacoman** [comment] 2019-07-10 17:53
same here

**Comment by JulianMelzig** [comment] 2019-08-21 07:48
same here

**Comment by asalom** [comment] 2019-08-21 08:33
It's happening to us too

**Comment by DracoRubi** [comment] 2019-09-24 09:18
Same issue here. I'm guessing no one found a solution? Besides switching to legacy build system, I mean.

**Comment by DracoRubi** [comment] 2019-10-01 15:23
Recently I updated my Firebase dependencies in CocoaPods and the issue seems to be solved.

**Comment by sergii-frost** [comment] 2019-10-16 14:29
@DracoRubi could you please share the part of your `Podfile` with versions of Firebase dependencies?

In my case I had:

```
pod 'Firebase/Core', '~> 4.0'
pod 'FirebaseMessaging', '~> 2.0'
```

I changed it to:

```
pod 'Firebase/Messaging', '4.8.2'
```

I am still getting error while archiving and am seeing this in frameworks for Pods: 

![image](https://user-images.githubusercontent.com/1237125/66928609-f4a49000-f031-11e9-8e93-50b87e7c23b8.png)

Using Xcode 11.1 with New build system. `rm -rf Podfile.lock; rm -rf Pods; rm -rf ...xcworkspace` did not help.

**Comment by DracoRubi** [comment] 2019-10-17 08:39
My podfile don't specify any version for the Firebase dependencies:

> pod 'Firebase/Core'
> pod 'FirebaseMessaging'
> pod 'Firebase/Analytics'

But reading the Podfile.lock file I can see that before updating the Firebase dependencies, I had the following:

> Firebase/Core (4.9.0)
> Firebase/Messaging (4.9.0)
> FirebaseAnalytics (4.0.9)

After updating the Firebase dependencies, I got those:

> Firebase/Core (6.7.0)
> Firebase/DynamicLinks (6.7.0)
> FirebaseAnalytics (6.1.1)

The main difference is that the new Firebase versions don't use `GoogleToolboForMac`, because it was replaced with `GoogleUtilities` (I suppose it's esentially the same, but they must have changed something in the internal structure, because I'm not getting the archive build failure anymore)

**Comment by thomasvl** [comment] 2020-06-16 14:40
Closing this out, since it sounds like most of the concerns have been address with other deps updates.

**Closed by thomasvl** 2020-06-16 14:40 UTC
